VERSION_ANALIZADOR = "1.4"
METODO_ANALISIS = "reglas_v1"

MAX_CARACTERES_TEXTO_GUARDADO = 5000
MIN_CARACTERES_TEXTO_UTIL = 30


REGLAS_CLASIFICACION = [
    {
        "categoria": "Posible conducta grave",
        "prioridad": "Alta",
        "peso_prioridad": 3,
        "palabras_clave": [
            "corrupción",
            "soborno",
            "cohecho",
            "extorsión",
            "amenaza",
            "amenazas",
            "amenaza de muerte",
            "violencia",
            "violencia física",
            "violencia psicologica",
            "violencia psicológica",
            "agresión",
            "agresiones",
            "golpes",
            "lesiones",
            "abuso",
            "abuso de autoridad",
            "abuso de funciones",
            "uso excesivo de la fuerza",
            "detención arbitraria",
            "privación de la libertad",
            "tortura",
            "trato cruel",
            "intimidación",
            "represalias",
            "encubrimiento",
            "alteración de documentos",
            "falsificación",
            "desaparición",
            "desvío de recursos",
            "malversación",
            "fraude",
        ],
    },
    {
        "categoria": "Derechos humanos / trato indigno",
        "prioridad": "Alta",
        "peso_prioridad": 3,
        "palabras_clave": [
            "derechos humanos",
            "vulneración",
            "vulneracion",
            "trato indigno",
            "trato degradante",
            "trato discriminatorio",
            "humillación",
            "humillacion",
            "discriminación",
            "discriminacion",
            "exclusión",
            "exclusion",
            "insultos",
            "burlas",
            "dignidad",
            "trato inhumano",
            "hostigamiento sexual",
            "acoso sexual",
        ],
    },
    {
        "categoria": "Conducta administrativa",
        "prioridad": "Media",
        "peso_prioridad": 2,
        "palabras_clave": [
            "negligencia",
            "incumplimiento",
            "omisión",
            "omision",
            "omisión de funciones",
            "omision de funciones",
            "abandono de funciones",
            "maltrato",
            "hostigamiento",
            "irregularidad",
            "falta administrativa",
            "trato indebido",
            "trato descortés",
            "trato descortes",
            "trato prepotente",
            "retardo",
            "demora",
            "dilación",
            "dilacion",
            "retardo injustificado",
            "demora injustificada",
            "negativa de atención",
            "negativa de atencion",
            "falta de atención",
            "falta de atencion",
            "mala atención",
            "mala atencion",
            "falta de respuesta",
            "trámite detenido",
            "tramite detenido",
            "expediente sin seguimiento",
            "documentación incompleta",
            "documentacion incompleta",
            "procedimiento irregular",
            "incumplimiento de horario",
        ],
    },
    {
        "categoria": "Documento probatorio / evidencia",
        "prioridad": "Media",
        "peso_prioridad": 2,
        "palabras_clave": [
            "evidencia",
            "prueba",
            "pruebas",
            "fotografía",
            "fotografia",
            "fotografías",
            "fotografias",
            "captura de pantalla",
            "video",
            "audio",
            "grabación",
            "grabacion",
            "testigo",
            "testigos",
            "declaración",
            "declaracion",
            "recibo",
            "comprobante",
            "documento probatorio",
            "anexo probatorio",
            "constancia médica",
            "constancia medica",
            "certificado médico",
            "certificado medico",
            "dictamen",
            "peritaje",
            "informe pericial",
        ],
    },
    {
        "categoria": "Documento de seguimiento",
        "prioridad": "Baja",
        "peso_prioridad": 1,
        "palabras_clave": [
            "solicitud",
            "seguimiento",
            "respuesta",
            "oficio",
            "anexo",
            "acuse",
            "acuse de recibido",
            "notificación",
            "notificacion",
            "informe",
            "informe de seguimiento",
            "constancia",
            "documentación",
            "documentacion",
            "memorándum",
            "memorandum",
            "circular",
            "turno",
            "remisión",
            "remision",
            "comparecencia",
            "citatorio",
            "acta",
            "minuta",
            "respuesta oficial",
            "documento anexo",
            "se adjunta",
            "se remite",
            "para conocimiento",
            "para los efectos conducentes",
        ],
    },
]