# Generated by Django 5.2.7 on 2026-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='fecha_documento',
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
