# Generated by Django 5.2.7 on 2026-05-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDocumentoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('requiere_atencion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to='expedientes.documento')),
            ],
        ),
    ]
