# Generated by Django 5.2.7 on 2026-05-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_analisisdocumentoia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('palabras_detectadas', models.TextField(blank=True)),
                ('requiere_atencion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='expedientes.documento')),
            ],
        ),
        migrations.DeleteModel(
            name='AnalisisDocumentoIA',
        ),
    ]
