# Generated by Django 6.0.4 on 2026-05-29 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_analisisdocumento_delete_analisisdocumentoia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisisdocumento',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Análisis de documento', 'verbose_name_plural': 'Análisis de documentos'},
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='categoria_final',
            field=models.CharField(blank=True, default='', help_text='Clasificación final definida por el usuario revisor.', max_length=100),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='comentario_revisor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='confianza',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Confianza aproximada del análisis en porcentaje.', max_digits=5),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='error_analisis',
            field=models.TextField(blank=True, default='', help_text='Mensaje técnico en caso de que el análisis falle.'),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='estado_revision',
            field=models.CharField(choices=[('pendiente_revision', 'Pendiente de revisión'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('corregido', 'Corregido'), ('error', 'Error en análisis')], default='pendiente_revision', max_length=30),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='justificacion',
            field=models.TextField(blank=True, default='', help_text='Explicación breve de por qué se sugirió esta clasificación.'),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='metodo_analisis',
            field=models.CharField(choices=[('reglas_v1', 'Reglas por palabras clave'), ('ia_externa', 'IA externa'), ('hibrido', 'Híbrido')], default='reglas_v1', max_length=30),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='prioridad_final',
            field=models.CharField(blank=True, default='', help_text='Prioridad final definida por el usuario revisor.', max_length=20),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_documentos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='texto_extraido',
            field=models.TextField(blank=True, default='', help_text='Texto extraído del PDF. En producción debe limitarse según políticas de privacidad.'),
        ),
        migrations.AddField(
            model_name='analisisdocumento',
            name='version_analizador',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
