# Generated by Django 5.2.7 on 2026-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_alter_analisisdocumento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_limite_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
