# Generated by Django 6.0.4 on 2026-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_alter_analisisdocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejadenuncia',
            name='folio',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
