# Generated by Django 6.0.4 on 2026-06-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_alter_quejadenuncia_folio'),
        ('expedientes', '0007_expediente_fecha_limite_estado'),
    ]

    operations = [
    ]
