# Generated by Django 5.2.7 on 2026-06-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_alter_quejadenuncia_folio'),
        ('expedientes', '0007_expediente_fecha_limite_estado'),
    ]

    operations = [
    ]
